var BackboneView = Backbone.View.extend({
    backLabel: null,

    /**
     * ViewNavigator hook for when page is loaded/resumed
     */
    showCallback: function () {
        // refresh view
        this.render();
    },

    events: {

    },

    /**
     * Initialize called once when view created
     */
    initialize: function(string, viewId) {
        this.string = string;
        this.title = "Title: " + viewId;
        this.view = this.$el;
        this.numRenders = 0;
    },

    /**
     * Render needs to be called when ViewNavigator fires ShowCompleted
     */
    render: function() {
        this.numRenders++;
        var bodyView = $('<div><b>Rendered ' + this.numRenders + ' times</b><hr/><li href="#" onclick="pushView()" class="viewNavigator_backButton">push view</li> <li href="#" onclick="popView()" class="viewNavigator_backButton">pop view</li><li href="#" onclick="replaceView()" class="viewNavigator_backButton">replace view</li> <li href="#" onclick="replaceWithRootView()" class="viewNavigator_backButton">replace with home view</li><hr>' + this.string + '</div>');
        this.$el.html(bodyView);
        //alert("rendered: " + this.viewId);
        return this;
    },

    showCallback: function () {
        this.render();
    }

});

$(document).ready( function() {

    //Setup the default view
    var myView = new BackboneView(getMeat(), Math.random().toString());

    //Setup the ViewNavigator
    window.viewNavigator = new ViewNavigator( 'body' );
    window.viewNavigator.pushView( myView );


} );

function pushView() {
    //create a view and push it onto the view navigator
    var view = new BackboneView(getMeat(), Math.random().toString());
    window.viewNavigator.pushView( view );
}

function replaceView() {
    //create a new view and replace the current view
    var view = new BackboneView(getMeat(), Math.random().toString());
    window.viewNavigator.replaceView( view );
}

function replaceWithRootView() {
    // clear the view stack down to the root view
    window.viewNavigator.jumpHome();
}

function popView() {
    //pop a view from the view navigator
    window.viewNavigator.popView();
}

function getMeat() {
    //randomly generate content
    //text string generated by http://baconipsum.com/
    var iterations = 1 + parseInt(Math.random() * 25);
    var result = "";
    for ( var i = 0; i < iterations; i ++ ) {
        result += "Pork chop corned beef meatloaf prosciutto flank, chuck andouille fatback hamburger cow ham turkey. Drumstick filet mignon boudin, salami beef ribs ball tip turducken frankfurter chuck. Pork chop swine chuck meatloaf capicola tri-tip. Pork belly venison bresaola flank, jerky ham hock short loin ground round corned beef salami pork filet mignon tri-tip sirloin. Tenderloin meatball corned beef, boudin brisket bresaola rump short loin tri-tip spare ribs pork belly cow.<hr>"
    }
    return result;
}